name: Build ZMK (user config)
on:
  workflow_dispatch:
  push:
    paths:
      - "config/**"
      - "build.yaml"
      - ".github/workflows/build.yml"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
    # Если ваш конфиг НЕ в корне (например firmware/zmk/),
    # добавьте явные пути:
    # with:
    #   build_matrix_path: firmware/zmk/build.yaml
    #   config_path: firmware/zmk/config

